### ISSUE TITLE
Build failed on windows: can't symlink

### ISSUE THREAD

**Issue by kjeremy** [nativeshell/examples#3] opened 2021-06-07 19:45 UTC
cargo run --release
   Compiling nativeshell_examples v0.1.0 (C:\projects\test\nativeshell\examples)
error: failed to run custom build command for `nativeshell_examples v0.1.0 (C:\projects\test\nativeshell\examples)`
> 
> Caused by:
  process didn't exit successfully: `C:\projects\test\nativeshell\examples\target\release\build\nativeshell_examples-f0d2532f983f3e08\build-script-build` (exit code: 101)
  --- stdout
> 
>  ** Build failed with error **
>
>  File operation failed: SymLink, target path: "C:\\projects\\test\\nativeshell\\examples\\target\\release\\build\\nativeshell_examples-53d87bf15d88f928\\out\\plugins\\flutter_export.h", source path: "C:\\flutter\\bin\\cache\\artifacts\\engine\\windows-x64-release\\flutter_export.h", error: A required privilege is not held by the client. (os error 1314)
>
> --- stderr
> thread 'main' panicked at 'explicit panic', build.rs:26:9
>  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ rustc --version
> rustc 1.52.1 (9bc8c42bb 2021-05-09)

$ flutter doctor -v
> [✓] Flutter (Channel master, 2.3.0-17.0.pre.236, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.3.0-17.0.pre.236 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3858cc655c (12 minutes ago), 2021-06-07 15:34:04 -0400
    • Engine revision 613d0a19fc
    • Dart version 2.14.0 (build 2.14.0-187.0.dev)

**Comment by knopp** [comment] 2021-06-07 19:48
Duplicate of https://github.com/nativeshell/nativeshell/issues/9.

Please [enable developer mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development), which is necessary to create symlinks on Windows. The error message will say this in next update.

**Closed as completed by knopp** 2021-06-07 19:48 UTC
